### ISSUE TITLE
Bug: Live mode logs cannot inspect

### ISSUE THREAD

**Issue by gtk-grafana** [grafana/logs-drilldown#142]
<img width="1728" alt="image" src="https://github.com/grafana/loki-explore/assets/109082771/f919624b-e229-4f3d-b47f-ff5e4704b782">

all logs say "no details available"

**Comment by sjmueller** [comment]
Curious why the solution here was to remove `Live mode`? Are there any plans to add it back to Explore logs? Without live, this new offering feels incomplete -- especially if you are trying to expand your audience beyond LogQL experts.
