### ISSUE TITLE
It's frustrating that there is no legend on the Log volume. In the app, quickly filtering level=error is more difficult. 

### ISSUE THREAD

**Issue by zizzpudding** [grafana/logs-drilldown#209]
Filtering level=error in explore can be done using the legend
See video

https://github.com/grafana/explore-logs/assets/573085/a14577ab-3337-474b-b2a4-bb6ca6e357c4

The volume histograms in the app don't have a legend. It's also frustrating that the only option on the pop up menu is "copy to clipboard" it would be nice to be able to filter by the legend in the popup and add to the search. 

https://github.com/grafana/explore-logs/assets/573085/ccf1576e-e98c-4267-b5c3-3cab67e1774f

**Comment by ivanahuckova** [comment]
App o11y is doing something similar, we might want to check it out.

**Comment by ivanahuckova** [comment]
MVP: Adding legend where you can filter out the noise in log volume service details page.
